version: '2'
services:
  web:
    build:
      context: .
      dockerfile: config/containers/Dockerfile-nginx
    volumes_from:
      - app
    links:
      - app
    ports:
      - '80:80'

  app:
    build:
      context: .
    env_file: .env
    environment:
      RAILS_ENV: $RAILS_ENV
    links:
      - db
    volumes_from:
      - container:fb-menu-api-sync:rw
    expose:
      - '3000'

  db:
    image: mysql:5.7
    volumes:
      - './.data/db:/var/lib/mysql'
    env_file: .env

volumes:
  fb-menu-api-sync:
    external: true
