default: &default
  adapter: mysql2
  encoding: utf8
  database: fancybite_menu_api
  username: root
  password: password
  host: db
  port: 3306

development:
  <<: *default
  database: fancybite_menu_api_dev

test:
  <<: *default
  database: fancybite_menu_api_test

production:
  <<: *default
  database: fancybite_menu_api_prod
