# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a209702ad2fc7f843f63ce3aabcb9a12bf22aa39a18661e71a8d1ed423abe1b1cbbd140bbcc7ac7262cda126623f5a9c6af053e704f4fa4780e890e09abadbb5

test:
  secret_key_base: 95749df1738c3acb018716593f0eefdf7bad5fccc3681d21773004d3c2a24d8ed1019b4bb1a6f4da4f653462a1a14310196d50092bc244c1d001836dc2a106fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
